const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFileSync}=require('child_process');
const sharp=require('sharp');
fs.mkdirSync('.data',{recursive:true});
const root=process.cwd(),folder=path.join(root,'كل الصور - All Images');const target='sensible-crab-500';const env={...process.env};delete env.CONVEX_DEPLOY_KEY;
const cli=path.join(root,'node_modules/convex/bin/main.js');
function run(fn,args={}){return JSON.parse(execFileSync(process.execPath,[cli,'run',fn,JSON.stringify(args),'--deployment',target],{env,encoding:'utf8',maxBuffer:8*1024*1024}));}
(async()=>{const menu=JSON.parse(fs.readFileSync('src/menu-data.json','utf8'));const existing=run('media:list');const items=[];fs.mkdirSync('assets/gallery',{recursive:true});for(const file of fs.readdirSync(folder).filter(f=>f.endsWith('.png'))){const original=path.join(folder,file);const bytes=fs.readFileSync(original);const sha256=crypto.createHash('sha256').update(bytes).digest('hex');const key=crypto.createHash('sha256').update(file).digest('hex').slice(0,20);let product,variant;for(const p of menu)for(const kind of ['plate','packaging'])if(p[kind]+'.png'===file){product=p;variant=kind;}const name=file.slice(0,-4);let ar,en;if(product){ar=product.ar;en=product.en;}else{const parts=name.split(' - ');ar=parts[0];en=parts.slice(1).join(' - ');}const category=product?(variant==='plate'?'plate':'packaging'):(/Logo|Pattern|Hero|Gathering|Single Dessert|Sweet Moment|Signature Packaging|Luxury$/.test(en)?'brand':'concept');const optimized=path.join('assets/gallery',key+'.webp');await sharp(bytes).resize({width:1200,withoutEnlargement:true}).webp({quality:85}).toFile(optimized);items.push({key,ar,en,category,sha256,...(product?{productId:product.id,variant}:{}),original,optimized,file});}
fs.writeFileSync('.data/gallery-upload-plan.json',JSON.stringify(items,null,2));const pending=items.filter(i=>!existing.some(e=>e.key===i.key&&e.sha256===i.sha256));if(pending.length){const urls=run('media:uploadUrls',{count:pending.length*2});let next=0;const uploaded=[];await Promise.all(Array.from({length:5},async()=>{while(next<pending.length){const n=next++,item=pending[n];const ids=[];for(const [index,file] of [item.optimized,item.original].entries()){const response=await fetch(urls[n*2+index],{method:'POST',headers:{'Content-Type':index?'image/png':'image/webp'},body:fs.readFileSync(file)});if(!response.ok)throw Error('Upload failed '+response.status);ids.push((await response.json()).storageId);}const {original,optimized,file,...metadata}=item;uploaded.push({...metadata,storageId:ids[0],originalId:ids[1]});fs.writeFileSync('.data/gallery-upload-checkpoint.json',JSON.stringify(uploaded));console.log('Uploaded '+uploaded.length+'/'+pending.length);}}));run('media:save',{items:uploaded});}
const remote=run('media:list');fs.writeFileSync('src/cloud-media.json',JSON.stringify(remote,null,2));const catalog=items.map(item=>{const r=remote.find(r=>r.key===item.key);if(!r?.url||!r?.originalUrl)throw Error('Missing uploaded media');return {...r,filename:item.file};});fs.writeFileSync('src/gallery-data.ts',`export const gallery = [\n${catalog.map(i=>`  {...${JSON.stringify(i)},local:require('../assets/gallery/${i.key}.webp')}`).join(',\n')}\n];\n`);console.log('DONE: '+catalog.length+' images, originals and optimized copies, deployment '+target);})().catch(e=>{console.error(e.message);process.exitCode=1});

