import React,{useCallback,useEffect,useRef,useState} from 'react';
import {api,customerToken,Order,OrderStatus,qatarToday,statusLabels} from './orders-api';
import {products,assetUrl} from './catalog';
import './orders.css';
type Props={ar:boolean};
const text=(ar:boolean,a:string,e:string)=>ar?a:e;
export function Checkout({ar,cart,onSaved,onBack,booking=false}:{ar:boolean;cart:Record<string,number>;onSaved:(order:Order)=>void;onBack:()=>void;booking?:boolean}) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [delivery,setDelivery]=useState(false);
  const requestKey=useRef(crypto.randomUUID());
  const t=(a:string,e:string)=>text(ar,a,e);
  const selected=products.filter(p=>(cart[p.id]||0)>0);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError('');const fields=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api<{order:Order}>('/orders',{method:'POST',body:{...fields,kind:booking?'booking':'order',fulfillment:delivery?'delivery':'pickup',items:selected.map(p=>({id:p.id,quantity:cart[p.id]})),ownerToken:customerToken(),requestKey:requestKey.current}});onSaved(result.order);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="order-form-wrap"><button className="text-button" onClick={onBack}>{t('العودة','Back')}</button><h2>{booking?t('احجز لحظتك الخاصة','Plan your special moment'):t('تفاصيل طلبك','Your order details')}</h2><p className="form-intro">{t('اختر الموعد المناسب. سنراجع طلبك قبل تأكيده. جميع المواعيد بتوقيت قطر.','Choose your preferred time. Your request will be reviewed before confirmation. All times are Qatar time.')}</p>
    <form onSubmit={submit} className="order-form"><fieldset disabled={busy}><label>{t('الاسم الكامل','Full name')}<input name="name" autoComplete="name" minLength={2} maxLength={80} required/></label><label>{t('رقم التواصل','Phone number')}<input name="phone" type="tel" autoComplete="tel" dir="ltr" placeholder="+974 …" pattern="\+?[0-9\s()\-]{7,24}" minLength={7} maxLength={24} required/></label><div className="form-row"><label>{t('يوم التجهيز','Preparation date')}<input name="day" type="date" min={qatarToday()} max={new Date(Date.now()+365*86400000).toISOString().slice(0,10)} required/></label><label>{t('الوقت المطلوب','Preferred time')}<input name="time" type="time" required/></label></div><label>{t('طريقة الاستلام','Fulfilment')}<select value={delivery?'delivery':'pickup'} onChange={e=>setDelivery(e.target.value==='delivery')}><option value="pickup">{t('استلام من المتجر','Store pickup')}</option><option value="delivery">{t('طلب توصيل — يحتاج تأكيدًا','Delivery request — subject to confirmation')}</option></select></label>{delivery&&<label>{t('العنوان والمنطقة','Address and area')}<textarea name="address" autoComplete="street-address" minLength={8} maxLength={300} required rows={2}/></label>}<label>{booking?t('تفاصيل المناسبة والكميات المطلوبة','Occasion and requested quantities'):t('ملاحظات إضافية (اختياري)','Additional notes (optional)')}<textarea name="notes" rows={3} minLength={booking?5:undefined} maxLength={1000} required={booking}/></label>
      {!booking&&<div className="checkout-summary">{selected.map(p=><div key={p.id}><span>{ar?p.ar:p.en} × {cart[p.id]}</span><span>{p.price === null ? t('عند التأكيد','On confirmation') : `${p.price*cart[p.id]} ${t('ر.ق','QAR')}`}</span></div>)}<div className="checkout-total"><strong>{t('إجمالي الطلب','Order total')}</strong><strong>{selected.some(p=>p.price===null) ? t('يُحدّد عند التأكيد','On confirmation') : `${selected.reduce((n,p)=>n+(p.price??0)*cart[p.id],0)} ${t('ر.ق','QAR')}`}</strong></div></div>}
      <p className="form-disclaimer">{t('الطلب يُحفظ في هذه النسخة التجريبية دون دفع. التوفر والتوصيل والسعر النهائي تحتاج تأكيد الفريق.','Your request is saved in this demo without payment. Availability, delivery and final pricing need team confirmation.')}</p><label className="consent"><input type="checkbox" required/>{t('أوافق على مشاركة بياناتي مع فريق دوبامين لمتابعة الطلب.','I agree to share my details with Dopamine to handle this request.')}</label></fieldset>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy||(!booking&&!selected.length)} type="submit">{busy?t('جارٍ حفظ طلبك…','Saving your request…'):t('إرسال الطلب','Submit request')}</button></form></div>;
}
export function OrderReceipt({ar,order,onContinue}:Props&{order:Order;onContinue:()=>void}){const t=(a:string,e:string)=>text(ar,a,e);return <div className="order-receipt"><svg className="receipt-mark" width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg><h2>{t('وصلنا طلبك','Request received')}</h2><p>{t('تم حفظه لفريق التجهيز، وهو بانتظار التأكيد.','It is saved for the preparation team and awaits confirmation.')}</p><strong dir="ltr">{order.id}</strong><p>{order.day} · {order.time} {t('بتوقيت قطر','Qatar time')}</p><a className="button primary" href="#/orders" onClick={onContinue}>{t('متابعة طلباتي','View my requests')}</a><button className="text-button" onClick={()=>{onContinue();location.hash='collection';}}>{t('متابعة التسوق','Continue shopping')}</button></div>}
function Status({status,ar}:Props&{status:OrderStatus}){return <span className={`order-status status-${status}`}>{statusLabels[status][ar?0:1]}</span>}
function Details({order,ar}:Props&{order:Order}){const t=(a:string,e:string)=>text(ar,a,e);return <><div className="order-info"><span>{order.fulfillment==='delivery'?t('توصيل مطلوب','Delivery requested'):t('استلام من المتجر','Store pickup')}</span><span>{order.kind==='booking'?t('حجز مناسبة','Occasion booking'):t('طلب منتجات','Product order')}</span></div>{order.items.length>0&&<ul className="order-lines">{order.items.map(p=><li key={p.id}><span>{ar?p.ar:p.en}</span><strong>× {p.quantity}</strong></li>)}</ul>}{order.address&&<p className="order-note"><b>{t('العنوان: ','Address: ')}</b>{order.address}</p>}{order.notes&&<p className="order-note"><b>{t('ملاحظات: ','Notes: ')}</b>{order.notes}</p>}<p className="order-amount">{order.kind==='booking'||order.total===null?t('السعر بعد مراجعة التفاصيل','Price after review'):`${t('إجمالي الطلب','Order total')}: ${order.total} ${t('ر.ق','QAR')}`}</p></>}
export function MyOrders({ar}:Props){const [orders,setOrders]=useState<Order[]>([]);const [busy,setBusy]=useState(true);const [error,setError]=useState('');const t=(a:string,e:string)=>text(ar,a,e);const load=useCallback(async()=>{setError('');try{const data=await api<{orders:Order[]}>('/my-orders',{method:'POST',body:{ownerToken:customerToken()}});setOrders(data.orders);}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[]);useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id);},[load]);return <section className="orders-page"><div className="orders-heading"><div><h1>{t('طلباتك، بكل تفاصيلها.','Your requests, in one place.')}</h1><p>{t('تابع حالة طلباتك وحجوزاتك المحفوظة من هذا المتصفح.','Track orders and bookings placed from this browser.')}</p></div><button className="button secondary" onClick={()=>{setBusy(true);load();}} disabled={busy}>{t('تحديث','Refresh')}</button></div>{error&&<p className="form-error" role="alert">{error}</p>}{busy&&<p role="status">{t('جارٍ تحميل الطلبات…','Loading requests…')}</p>}{!busy&&!error&&!orders.length&&<div className="orders-empty"><h2>{t('أول لحظة حلوة تبدأ هنا','Your first sweet moment starts here')}</h2><p>{t('أضف منتجات إلى الحقيبة أو احجز لمناسبتك القادمة.','Add products to your bag or book for your next occasion.')}</p><a className="button primary" href="#collection">{t('تصفح المجموعة','Browse the collection')}</a></div>}<div className="customer-orders">{orders.map(order=><article className="order-card" key={order.id}><div className="order-card-top"><strong dir="ltr">{order.id}</strong><Status ar={ar} status={order.status}/></div><h2>{order.day} <span>· {order.time}</span></h2><p className="timezone">{t('موعد التجهيز المطلوب · توقيت قطر','Requested preparation · Qatar time')}</p><Details ar={ar} order={order}/></article>)}</div><p className="form-disclaimer">{t('احتفظ برقم الطلب. عرض الطلبات مرتبط بهذا المتصفح؛ حذف بياناته يفقد الوصول إلى سجلّك هنا.','Keep your request number. Tracking is linked to this browser; clearing its data removes access to your history here.')}</p></section>}
export function Booking({ar}:Props){const [saved,setSaved]=useState<Order|null>(null);return <section className="booking-page">{saved?<OrderReceipt ar={ar} order={saved} onContinue={()=>{}}/>:<Checkout ar={ar} cart={{}} booking onSaved={setSaved} onBack={()=>{location.hash='collection';}}/>}</section>}
export function AdminOrders({ar}:Props){
  const [token,setToken]=useState(()=>sessionStorage.getItem('dopamine-admin-session')||'');const [orders,setOrders]=useState<Order[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [day,setDay]=useState(qatarToday());const [status,setStatus]=useState('all');const [search,setSearch]=useState('');const [updating,setUpdating]=useState('');const [stamp,setStamp]=useState('');const t=(a:string,e:string)=>text(ar,a,e);
  const load=useCallback(async()=>{if(!token)return;try{const result=await api<{orders:Order[]}>('/admin/orders',{token});setOrders(result.orders);setError('');setStamp(new Date().toLocaleTimeString(ar?'ar-QA':'en-GB'));}catch(e){if((e as {status?:number}).status===401){setToken('');sessionStorage.removeItem('dopamine-admin-session');}setError((e as Error).message);}finally{setBusy(false);}},[token,ar]);
  useEffect(()=>{if(!token)return;setBusy(true);load();const timer=setInterval(load,10000);return()=>clearInterval(timer);},[load,token]);
  async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const key=String(new FormData(e.currentTarget).get('key'));try{const result=await api<{token:string}>('/admin/login',{method:'POST',body:{key}});sessionStorage.setItem('dopamine-admin-session',result.token);setToken(result.token);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function update(order:Order,next:string){setUpdating(order.id);setError('');try{const result=await api<{order:Order}>(`/admin/orders/${order.id}`,{method:'PATCH',token,body:{status:next,updatedAt:order.updatedAt}});setOrders(old=>old.map(o=>o.id===order.id?result.order:o));}catch(e){setError((e as Error).message);}finally{setUpdating('');}}
  if(!token)return <section className="admin-login"><h1>{t('مساحة فريق دوبامين','Dopamine team space')}</h1><p>{t('سجّل الدخول لمتابعة الطلبات ومواعيد التجهيز.','Sign in to manage requests and preparation dates.')}</p><form className="order-form" onSubmit={login}><label>{t('مفتاح دخول الإدارة','Admin access key')}<input name="key" type="password" autoComplete="current-password" required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?t('جارٍ الدخول…','Signing in…'):t('دخول الإدارة','Sign in')}</button></form></section>;
  const today=qatarToday();const active=orders.filter(o=>!['cancelled','completed'].includes(o.status));const shown=orders.filter(o=>(!day||o.day===day)&&(status==='all'||o.status===status)&&`${o.name} ${o.phone} ${o.id}`.toLowerCase().includes(search.toLowerCase().trim()));const groups=[...new Set(shown.map(o=>o.day))].sort();
  return <section className="orders-page admin-page"><div className="orders-heading"><div><h1>{t('جدول التجهيز','Preparation schedule')}</h1><p>{t('كل طلب، في موعده. تحديث تلقائي كل ١٠ ثوانٍ.','Every request, on time. Refreshes every 10 seconds.')}</p></div><div className="admin-actions"><button className="button secondary" onClick={()=>{setBusy(true);load();}} disabled={busy}>{t('تحديث','Refresh')}</button><button className="text-button" onClick={async()=>{try{await api('/admin/logout',{method:'POST',token});}catch{}finally{sessionStorage.removeItem('dopamine-admin-session');setToken('');setOrders([]);}}}>{t('خروج','Sign out')}</button></div></div><div className="order-stats"><div><strong>{active.filter(o=>o.day===today).length}</strong><span>{t('للتجهيز اليوم','To prepare today')}</span></div><div><strong>{orders.filter(o=>o.status==='pending').length}</strong><span>{t('بانتظار التأكيد','Awaiting confirmation')}</span></div><div><strong>{active.filter(o=>o.day<today).length}</strong><span>{t('طلبات متأخرة','Overdue requests')}</span></div><div><strong>{active.filter(o=>o.day>today).length}</strong><span>{t('مواعيد قادمة','Upcoming requests')}</span></div></div>
    <div className="admin-filters"><label>{t('يوم التجهيز','Preparation day')}<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><button className="text-button" onClick={()=>setDay(today)}>{t('اليوم','Today')}</button><button className="text-button" onClick={()=>setDay('')}>{t('كل الأيام','All dates')}</button><label>{t('الحالة','Status')}<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t('كل الحالات','All statuses')}</option>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label[ar?0:1]}</option>)}</select></label><label className="search-label">{t('بحث بالعميل أو رقم الطلب','Find customer or request')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('الاسم، الهاتف، رقم الطلب','Name, phone, request ID')}/></label></div>
    <div className="results-meta"><span>{shown.length} {t('طلب','requests')}</span><span aria-live="polite">{busy?t('جارٍ التحديث…','Refreshing…'):stamp?`${t('آخر تحديث','Updated')} ${stamp}`:''}</span></div>{error&&<p role="alert" className="form-error">{error}</p>}{!busy&&!error&&!shown.length&&<div className="orders-empty"><h2>{t('لا توجد طلبات مطابقة','No matching requests')}</h2><p>{t('جرّب كل الأيام أو غيّر فلاتر البحث. ستظهر الطلبات الجديدة تلقائيًا.','Try all dates or change the filters. New requests appear automatically.')}</p><button className="button secondary" onClick={()=>{setDay('');setStatus('all');setSearch('');}}>{t('عرض جميع الطلبات','Show all requests')}</button></div>}
    {groups.map(date=><div className="day-group" key={date}><h2>{new Intl.DateTimeFormat(ar?'ar-QA':'en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Qatar'}).format(new Date(date+'T12:00:00+03:00'))}</h2>{shown.filter(o=>o.day===date).map(order=><article className="admin-order" key={order.id}><div className="order-time"><strong>{order.time}</strong><span>{t('توقيت قطر','Qatar time')}</span></div><div className="admin-order-content"><div className="order-card-top"><h3>{order.name}</h3><Status ar={ar} status={order.status}/></div><div className="customer-contact"><a href={`tel:${order.phone.replace(/[^\d+]/g,'')}`} dir="ltr">{order.phone}</a><span dir="ltr">{order.id}</span></div><Details ar={ar} order={order}/></div><label className="status-control">{t('تحديث حالة الطلب','Update status')}<select value={order.status} disabled={!!updating} onChange={e=>update(order,e.target.value)}>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label[ar?0:1]}</option>)}</select>{updating===order.id&&<span role="status">{t('جارٍ الحفظ…','Saving…')}</span>}</label></article>)}</div>)}
  </section>;
}
