export type OrderStatus = 'pending'|'confirmed'|'preparing'|'ready'|'completed'|'cancelled';
export type Order = { id:string; kind:'order'|'booking'; name:string; phone:string; day:string; time:string; fulfillment:'pickup'|'delivery'; address:string; notes:string; total:number|null; currency:string; status:OrderStatus; createdAt:string; updatedAt:string; items:{id:string;ar:string;en:string;price:number|null;quantity:number}[] };
export const statusLabels: Record<OrderStatus,[string,string]> = { pending:['بانتظار التأكيد','Awaiting confirmation'],confirmed:['مؤكد','Confirmed'],preparing:['قيد التجهيز','Preparing'],ready:['جاهز','Ready'],completed:['تم التسليم','Completed'],cancelled:['ملغي','Cancelled'] };
export function qatarToday() { return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qatar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()); }
export function customerToken() { let token=localStorage.getItem('dopamine-customer-token');if(!token){token=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem('dopamine-customer-token',token);}return token; }
const apiBase=process.env.EXPO_PUBLIC_ORDERS_API_URL || (typeof location !== 'undefined' && ['localhost','127.0.0.1'].includes(location.hostname) ? `${location.protocol}//${location.hostname}:8082` : '');
export async function api<T>(path:string, options:{method?:string;body?:unknown;token?:string}={}):Promise<T> {
  const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);
  try { const response=await fetch(`${apiBase}/api${path}`,{method:options.method || 'GET',headers:{'Content-Type':'application/json',...(options.token ? {Authorization:`Bearer ${options.token}`} : {})},body:options.body === undefined ? undefined : JSON.stringify(options.body),signal:controller.signal});const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error || 'Request failed'),{status:response.status});return data; } catch(error) { if(error instanceof Error && 'status' in error)throw error;throw new Error('تعذّر الاتصال بخدمة الطلبات. حاول مجددًا. / Orders service unavailable. Please retry.'); } finally { clearTimeout(timeout); }
}
